### PR TITLE
Add ReadM and Parser instances for more stdlib types, closes #4

### LINKED ISSUE #4: Add ReadM (and related) for other types
e.g. Short, Long, BigInt

Should these be placed in the same place as the [existing ones](https://github.com/bmjames/scala-optparse-applicative/blob/f0523021398885761b0b96a9be6afb1382c12f1c/src/main/scala/net/bmjames/opts/builder/Builder.scala) or in a separate place?

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by adelbertc** [comment]
Note: There is currently overloading on `short` and `long` for the `ReadM[Short]` and `ReadM[Long]` - the names were chosen to match the existing `str` and `int` names. Let me know if you'd like me to name them differently.

**Comment by adelbertc** [comment]
I think prefixing with `read` sounds OK and less intrusive than having them not imported from `net.bmjames.opts` - thoughts?

**Comment by adelbertc** [comment]
+ @shajra

**Comment by bmjames** [comment]
@adelbertc let's go with the `read` prefixes for now, then.

**Pull request merged**
